In [59]:
-

In [60]:
m, s, b = make_artificial_dataset(motif_length=6, n_motives=1, n_sequences=10, p=1, sequence_length=12)
print 
for i in s:
    print i[1]
print 
print b


ATTTCTCGCCCC
GTAAGTTACATC
TACGGCGGAGAT
TAAGCCTATGTC
ACACCTGGCACC
AAAGTCTACCCA
TGGAATCACATT
ACGGAAGCAGTC
TGCCTTCATGTT
GGACACGAAATC

000111111000


In [50]:
pwms = get_pwms(num=1, length=3, exp=1.1)

0 original random:
[[ 0.77810038  0.35525653  0.93556243]
 [ 0.48273482  0.14647413  0.38810055]
 [ 0.42038125  0.42296065  0.4781181 ]
 [ 0.2916239   0.11239531  0.23220642]]

0 after 1st normalization:
[[ 0.39440616  0.34255242  0.45996469]
 [ 0.24469026  0.14123616  0.19080774]
 [ 0.21308427  0.40783541  0.23506442]
 [ 0.14781931  0.10837601  0.11416315]]

final pwms:
[[[ 0.40996356  0.34832756  0.48223591]
  [ 0.24248538  0.13144032  0.18319693]
  [ 0.20826378  0.42200881  0.23044548]
  [ 0.13928729  0.09822331  0.10412167]]]


In [47]:
print pwms[0].sum(axis=0)

[ 1.  1.  1.]


In [41]:
x = np.random.random_sample((2, 3))
print x

[[ 0.38047791  0.35362137  0.718556  ]
 [ 0.96832642  0.96721669  0.09613211]]
